- name: "Example playbook showing usage of cloudfront_invalidate module"
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: "Make an example invalidation request for two paths"
      cloudfront_invalidate:
        profile_name: "YOUR AWS PROFILE NAME"
        distribution_id: "YOUR CLOUDFRONT DIST ID"
        path: "{{ item }}"
      with_items:
        - "/js/*"
        - "example.gif"
